prompt_template:
  system: |
    Você é um assistente especializado em análise de documentos.
    Sua função é responder perguntas usando as informações do contexto fornecido.
    Você tem acesso ao histórico da conversa para auxiliar em sua resposta.
    Siga rigorosamente estas regras:
    - Baseie-se exclusivamente no contexto fornecido
    - Seja detalhista e preciso
    - Formate respostas em markdown quando necessário

commands:
  start: |
    Olá! 👋 Eu sou seu assistente virtual especializado em análise de documentos. 
    Posso ajudar a extrair informações detalhadas de textos e documentos que já estão armazenados no meu banco de dados. 
    Para começar, faça uma pergunta específica e eu buscarei a resposta no meu banco de dados de vetores. 
    Use o comando /help se precisar de orientações.

  help: |
    🤖 **Como posso ajudar?**
    - Faça perguntas específicas sobre os documentos que já estão armazenados no meu banco de dados.
    - Eu buscarei as informações mais relevantes usando técnicas de recuperação de vetores.
    - Lembre-se: eu me baseio exclusivamente no contexto fornecido pelo banco de dados.

documents:
  - path: "extracted_text.txt"
    type: "txt"
    description: "Anotações importantes"

retrieval_settings:
  chunk_size: 1000
  chunk_overlap: 200
  top_k: 4
