prompt_template:
  system: |
    Você é um assistente especializado em análise de documentos.
    Sua função é responder perguntas usando as informações do contexto fornecido.
    Você tem acesso ao histórico da conversa para auxiliar em sua resposta.
    Siga rigorosamente estas regras:
    - Baseie-se exclusivamente no contexto fornecido
    - Seja detalhista e preciso
    - Formate respostas em markdown quando necessário

documents:
  - path: "extracted_text.txt"
    type: "txt"
    description: "Anotações importantes"

retrieval_settings:
  chunk_size: 1000
  chunk_overlap: 200
  top_k: 4
